### ISSUE TITLE
This action doesn't seem to have ever worked

### ISSUE THREAD

**Issue by ikatz-drizly** [keithweaver/aws-s3-github-action#6]
I see a host of issues
* input names that don't match the documentation
* improper quoting
* improper bracketing
* if-statement logic that doesn't match the comments
* inconsistent capitalization of variable names

**Comment by gsaraf** [comment]
I don't think this repo is still active, unfortunately. I've forked it to https://github.com/gsaraf/aws-s3-github-action, fixed [I think] all of these problems and published on the marketplace at https://github.com/marketplace/actions/aws-s3-github-action-supported.

I'm happy to continue supporting this action - feel free to open a PR there and I will review promptly.

**Comment by 825i** [comment]
> I don't think this repo is still active, unfortunately. I've forked it to https://github.com/gsaraf/aws-s3-github-action, fixed [I think] all of these problems and published on the marketplace at https://github.com/marketplace/actions/aws-s3-github-action-supported.
> 
> I'm happy to continue supporting this action - feel free to open a PR there and I will review promptly.

Hi mate! You have issues disabled on your forked repo so I am commenting here. I was wondering about adding a function to run on a schedule.

The example given shows the source as local and destination as the s3 bucket, can I swap them? Basically what I want to do is download the last 3 metadata files that were sent to my s3 bucket, join them into one metadata.json and then .zip that for email.

Btw, thanks for fixing the script. <3

**Comment by gsaraf** [comment]
Hi @pythonInRelay! I've enabled issues in the fork. Sorry - didn't know I had to do that :p

I'm not entirely sure I understand what you mean about the scheduling. You can make a workflow run on a schedule using standard github actions syntax.

Both the source and destination can be either local or s3 paths, so what you suggest should work fine :)
